spring.datasource.url=jdbc:postgresql://ep-delicate-dawn-aibg6ira-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_ItBDoHYZ6l4N&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

#Log out sql queries or comment these lines out with a hashtag
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE